#!/bin/bash -e

if [ "$1" == "-no-strip" ]; then
	name=$(echo "$2" | cut -f 1 -d '.')

	{ cat "$2" | sed -e "1!b" -e '/#/d' ; cat /bin/lib-bfm.lua } | /bin/bfpp | /bin/bflabels | /bin/bfdata | sed '/^#/ d' | /bin/bfasm > "${2%.*}.b"
else
	name=$(echo "$1" | cut -f 1 -d '.')

	{ cat "$1" | sed -e "1!b" -e '/#/d' ; cat /bin/lib-bfm.lua } | /bin/bfpp | /bin/bflabels | /bin/bfdata | sed '/^#/ d' | /bin/bfasm | /bin/bfstrip > "${1%.*}.b"
fi
