#!/bin/bash -e

set -o pipefail

{ cat <<<"#define NEWLINE ÿ" ; cat "$1" | sed -e "1!b" -e '/#/d' ; } | gcc -E -I. -Ilib - -o "$1.i"
perl -pe "s/\xFF/\x0A/g;" < "$1.i" | /bin/labels.pl | sed '/^#/ d' > "$1.p"
rm -f "$1.i"
