#!/bin/bash

function quit {
	rm -f core-diff.patch test-files.tar.gz operation.log
	make test-clean
	exit 0
}

make all setup test 2>&1 | tee operation.log

tar -czf test-files.tar.gz test/*
diff bfasm.c bfasm-orig.c > core-diff.patch

tar -czf report-$RANDOM.tar.gz operation.log test-files.tar.gz core-diff.patch

quit
