{"AA", "asmbf_first $I"},
{"AB", "asmbf_last $I"},
{"AC", "asmbf_pre $I"},
{"AD", "asmbf_post $I"},
{"AE", "asmbf_immed($C);$S"},
{"AF", "asmbf_clear($C);$S"},
{"AG", "asmbf_add($C, $S$C);$S"},
{"AH", "asmbf_and($C, $S$C);$S"},
{"AI", "asmbf_dec($C);$S"},
{"AJ", "asmbf_div($C, $S$C);$S"},
{"AK", "asmbf_eq($C, $S$C);$S"},
{"AL", "asmbf_ge($C, $S$C);$S"},
{"AM", "asmbf_gt($C, $S$C);$S"},
{"AN", "asmbf_in($C);$S"},
{"BL", "asmbf_inc($C);$S"},
{"AO", "asmbf_jmp($C);$S"},
{"AP", "asmbf_jnz($C, $S$C);$S"},
{"AQ", "asmbf_jz($C, $S$C);$S"},
{"AR", "$S$S$M$Sif(tape[1]==$C)tape[0]=1;$S$S"},
{"AS", "asmbf_le($C, $S$C);$S"},
{"AT", "asmbf_lt($C, $S$C);$S"},
{"AU", "asmbf_mod($C, $S$C);$S"},
{"AV", "asmbf_mov($C, $S$C);$S"},
{"AW", "asmbf_mul($C, $S$C);$S"},
{"AY", "asmbf_neg($C);$S"},
{"FM", "asmbf_not($C);$S"},
{"BA", "asmbf_or($C, $S$C);$S"},
{"BB", "asmbf_out($C);$S"},
{"BC", "asmbf_pop($C, $S$C);$S"},
{"BD", "asmbf_push($C, $S$C);$S"},
{"BE", "asmbf_rcl($C, $S$C, $S$C);$S"},
{"BF", "asmbf_sto($C, $S$C, $S$C);$S"},
{"BG", "asmbf_sub($C, $S$C);$S"},
{"BH", "asmbf_swp($C, $S$C);$S"},
{"BI", "asmbf_clear($C);$S"},
{"BJ", "asmbf_ret($C);$S"},
{"BK", "asmbf_end $I"},
{"BM", "asmbf_log($C);$S"},
{"BN", "asmbf_asl($C);$S"},
{"BO", "asmbf_asr($C);$S"},
{"BP", "asmbf_pow($C, $S$C);$S"},
{"BR", "asmbf_srv($C);$S"},
{"BS", "asmbf_amp($C, $S$C, $S$C);$S"},
{"BT", "asmbf_smp($C, $S$C, $S$C);$S"},
{"BU", "asmbf_immed($C);$S"}