{"AA", "asmbf_first $I"},
{"AB", "asmbf_last $I"},
{"AC", "asmbf_pre $I"},
{"AD", "asmbf_post $I"},
{"AE", "asmbf_immed($C);$S"},
{"AF", "asmbf_clear($C);$S"},
{"AG", "asmbf_add($C, $S$C);$S"},
{"AH", "asmbf_and($C, $S$C);$S"},
{"AI", "asmbf_dec($C);$S"},
{"AJ", "asmbf_div($C, $S$C);$S"},
{"AK", "asmbf_eq($C, $S$C);$S"},
{"AL", "asmbf_ge($C, $S$C);$S"},
{"AM", "asmbf_gt($C, $S$C);$S"},
{"AN", "asmbf_in($C);$S"},
{"BL", "asmbf_inc($C);$S"},
{"AO", "asmbf_jmp($C);$S"},
{"AP", "asmbf_jnz($C, $S$C);$S"},
{"AQ", "asmbf_jz($C, $S$C);$S"},
{"AR", "$S$S$M$Sif(tape[1]==$C)tape[0]=1;$S$S"},
{"AS", "asmbf_le($C, $S$C);$S"},
{"AT", "asmbf_lt($C, $S$C);$S"},
{"AU", "asmbf_mod($C, $S$C);$S"},
{"AV", "asmbf_mov($C, $S$C);$S"},
{"AW", "asmbf_mul($C, $S$C);$S"},
{"AY", "asmbf_neg($C);$S"},
{"FM", "asmbf_not($C);$S"},
{"BA", "asmbf_or($C, $S$C);$S"},
{"BB", "asmbf_out($C);$S"},
{"BC", "asmbf_pop($C, $S$C);$S"},
{"BD", "asmbf_push($C, $S$C);$S"},
{"BE", "asmbf_rcl($C, $S$C, $S$C);$S"},
{"BF", "asmbf_sto($C, $S$C, $S$C);$S"},
{"BG", "asmbf_sub($C, $S$C);$S"},
{"BH", "asmbf_swp($C, $S$C);$S"},
{"BI", "asmbf_clear($C);$S"},
{"BJ", "asmbf_ret($C);$S"},
{"BK", "asmbf_end $I"},
{"BM", "asmbf_log($C);$S"},
{"BN", "asmbf_asl($C);$S"},
{"BO", "asmbf_asr($C);$S"},
{"BP", "asmbf_pow($C, $S$C);$S"},
{"BR", "asmbf_srv($C);$S"},
{"BS", "asmbf_amp($C, $S$C, $S$C);$S"},
{"BT", "asmbf_smp($C, $S$C, $S$C);$S"},
{"BU", "asmbf_immed($C);$S"},
{"FM", "asmbf_rse_toggle();$S"},
{"BV", "asmbf_ceq($C, $S$C, $S$C);$S"},
{"BW", "asmbf_cne($C, $S$C, $S$C);$S"},
{"BX", "asmbf_cle($C, $S$C, $S$C);$S"},
{"BY", "asmbf_clt($C, $S$C, $S$C);$S"},
{"FO", "asmbf_cge($C, $S$C, $S$C);$S"},
{"CA", "asmbf_cgt($C, $S$C, $S$C);$S"},
{"CB", "asmbf_cjn($C);$S"},
{"CC", "asmbf_cjz($C);$S"},
{"CD", "asmbf_cadd($C, $S$C);$S"},
{"CE", "asmbf_csub($C, $S$C);$S"},
{"CF", "asmbf_cmul($C, $S$C);$S"},
{"CG", "asmbf_cdiv($C, $S$C);$S"},
{"CH", "asmbf_cmod($C, $S$C);$S"},
{"CI", "asmbf_casl($C);$S"},
{"CJ", "asmbf_casr($C);$S"},
{"CK", "asmbf_cpow($C, $S$C);$S"},
{"CL", "asmbf_cpush($C, $S$C);$S"},
{"CM", "asmbf_cpop($C, $S$C);$S"},
{"CN", "asmbf_cswp($C, $S$C);$S"},
{"CO", "asmbf_csrv($C);$S"},
{"CP", "asmbf_cmov($C, $S$C);$S"},
{"CR", "asmbf_crcl($C, $S$C, $S$C);$S"},
{"CS", "asmbf_csto($C, $S$C, $S$C);$S"},
{"CT", "asmbf_camp($C, $S$C, $S$C);$S"},
{"CU", "asmbf_csmp($C, $S$C, $S$C);$S"},
{"CV", "asmbf_band($C, $S$C);$S"},
{"CW", "asmbf_bor($C, $S$C);$S"},
{"CX", "asmbf_bxor($C, $S$C);$S"},
{"CY", "asmbf_bneg($C, $S$C);$S"},
{"DA", "asmbf_cflip();$S"},
{"DB", "asmbf_shr($C, $S$C);$S"},
{"DC", "asmbf_shl($C, $S$C);$S"},
{"DD", "asmbf_cout($C);$S"},
{"DE", "asmbf_cin($C);$S"},
{"DF", "asmbf_cpar($C);$S"},
{"DG", "asmbf_par($C, $S$C);$S"},
{"DH", "asmbf_gcd($C, $S$C);$S"},
{"DI", "asmbf_cgcd($C, $S$C);$S"},
{"DJ", "asmbf_cret($C);$S"},
{"DK", "asmbf_fmul($C);$S"},
{"DL", "asmbf_fdiv($C);$S"},
{"DM", "asmbf_freduce($C);$S"},
{"DN", "asmbf_fadd($C);$S"},
{"DO", "asmbf_fsub($C);$S"},
{"DP", "asmbf_dup($C);$S"},
{"DR", "asmbf_cdup($C);$S"},
{"DS", "asmbf_candeq($C, $S$C);$S"},
{"DT", "asmbf_candne($C, $S$C);$S"},
{"DU", "asmbf_candle($C, $S$C);$S"},
{"DW", "asmbf_candge($C, $S$C);$S"},
{"DX", "asmbf_candlt($C, $S$C);$S"},
{"DY", "asmbf_candgt($C, $S$C);$S"},
{"EA", "asmbf_coreq($C, $S$C);$S"},
{"EB", "asmbf_corne($C, $S$C);$S"},
{"EC", "asmbf_corle($C, $S$C);$S"},
{"ED", "asmbf_corge($C, $S$C);$S"},
{"EE", "asmbf_corlt($C, $S$C);$S"},
{"EF", "asmbf_corgt($C, $S$C);$S"},
{"EG", "asmbf_cxoreq($C, $S$C);$S"},
{"EH", "asmbf_cxorne($C, $S$C);$S"},
{"EI", "asmbf_cxorle($C, $S$C);$S"},
{"EJ", "asmbf_cxorge($C, $S$C);$S"},
{"EK", "asmbf_cxorlt($C, $S$C);$S"},
{"EL", "asmbf_cxorgt($C, $S$C);$S"},
{"EM", "asmbf_ots($C, $S$C, $S$C);$S"},
{"EN", "asmbf_cots($C, $S$C, $S$C);$S"},
{"EO", "asmbf_dsc($C);$S"},
{"EP", "asmbf_sgt($C, $S$C, $S$C);$S"},
{"ER", "asmbf_spt($C, $S$C, $S$C);$S"},
{"ES", "asmbf_sle($C, $S$C);$S"},
{"ET", "asmbf_tps($C, $S$C, $S$C);$S"},
{"EU", "asmbf_fps($C);$S"},
{"EW", "asmbf_fpo($C);$S"},
{"EX", "asmbf_sgn($C);$S"},
{"EY", "asmbf_abs($C);$S"},
{"FB", "asmbf_sneg($C);$S"},
{"FA", "asmbf_smul($C, $S$C);$S"},
{"FC", "asmbf_sdiv($C, $S$C);$S"},
{"FD", "asmbf_smod($C, $S$C);$S"},
{"FE", "if(tape[Q]){$S"},
{"FF", "}$S"},
{"FG", "asmbf_ssub($C, $S$C);$S"},
{"FH", "asmbf_sadd($C, $S$C);$S"},
{"FI", "asmbf_dup2($C);$S"},
{"FJ", "asmbf_axl($C);$S"},
{"FK", "asmbf_xgt($C, $S$C);$S"},
{"FL", "asmbf_xle($C, $S$C);$S"},
{"FM", "asmbf_xlt($C, $S$C);$S"},
{"FN", "asmbf_xge($C, $S$C);$S"}
